// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var dealerH, deck, playerH,
        _this = this;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      dealerH = this.get('dealerHand');
      playerH = this.get('playerHand');
      playerH.on('turnOver', function() {
        var _results;
        if (dealerH.models.length < 3) {
          dealerH.models[0].flip();
        }
        _results = [];
        while ((dealerH.scores()[0] < 21 && dealerH.scores()[1] < 17) || (dealerH.scores()[0] < 17 && dealerH.scores()[1] > 21)) {
          if (dealerH.scores()[0] < 17) {
            _results.push(dealerH.hit());
          } else {
            dealerH.gameOver();
            console.log(dealerH.scores());
            break;
          }
        }
        return _results;
      });
      return dealerH.on('gameSet', function() {
        var dealerScore, playerScore;
        dealerScore = dealerH.scores()[0] > dealerH.scores()[1] ? dealerH.scores()[0] : dealerH.scores()[1];
        playerScore = playerH.scores()[1] > 21 ? playerH.scores()[0] : playerH.scores()[1] === 1 ? playerH.scores()[0] : playerH.scores()[1];
        console.log("dealer " + dealerScore + " player " + playerScore);
        if (dealerScore === playerScore) {
          alert("draw!");
        }
        if (dealerScore > playerScore) {
          return alert("you lose");
        } else {
          return alert("you win");
        }
      });
    };

    return App;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
