// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      _ref = Hand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      return this.checkBlackJack();
    };

    Hand.prototype.checkBlackJack = function() {
      if (this.scores() === 21 || this.scores() > 21) {
        return this.gameOver();
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('turnOver', this);
    };

    Hand.prototype.split = function() {
      return console.log(this.models);
    };

    Hand.prototype.gameOver = function() {
      console.log('game OVer!');
      if (this.scores() === 21) {
        console.log('blackJack');
        console.log(this);
        this.blackJack();
      }
      if (this.scores() > 21) {
        console.log('busted');
        return this.busted();
      }
    };

    Hand.prototype.busted = function() {
      return this.trigger('busted', this);
    };

    Hand.prototype.blackJack = function() {
      return this.trigger('blackJack', this);
    };

    Hand.prototype.scores = function() {
      var finalScore, hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      return finalScore = hasAce ? score + 10 < 22 ? score + 10 : score : score;
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

/*
//@ sourceMappingURL=Hand.map
*/
